### ISSUE TITLE
OSError: Unable to run gpg - it may not be available.

### ISSUE THREAD

**Issue by flizzywine** [realgud/realgud#183]
In Mac OSX 10.12. I ran M-x load-library realgud, then M-x realgud:pdb
it reported:
Traceback (most recent call last):
  File "/usr/local/bin/pdb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pdb/pdb.py", line 107, in main
    passwd = pstore.get(args.type)
  File "/usr/local/lib/python2.7/site-packages/pdb/pdb.py", line 55, in get
    gpg = gnupg.GPG(gnupghome=self._gpghome)
  File "/usr/local/lib/python2.7/site-packages/gnupg.py", line 759, in __init__
    raise OSError(msg)
OSError: Unable to run gpg - it may not be available.

**Comment by flizzywine** [comment]
Oh, I got it.

**Comment by ranjana-raveesh** [comment]
Can u help how you fixed it?

**Comment by kierun** [comment]
@ranjana-raveesh use `gpg = gnupg.GPG("gpg", verbose=True)` where the first argument is the name of the GnuPG executable.
